### ISSUE TITLE
Upgrade snowplow_utils package version

### ISSUE THREAD

**Issue by georgewoodhead** [snowplow/dbt-snowplow-mobile#43]
### Describe the bug
This package uses an older version of snowplow_utils which will cause dependancy conflicts if using other snowplow packages which depend on different versions of snowplow_utils in your dbt project.

### Steps to reproduce
1. Use both the latest mobile and web packages in your dbt project `packages.yml` file:
```yaml 
packages:
  - package: snowplow/snowplow_web
    version: 0.9.2
  - package: snowplow/snowplow_mobile
    version: 0.5.3
```

2. Run `dbt deps`.

### Expected results
No error, all packages install successfully.

### Actual results
```
Version error for package snowplow/snowplow_utils: Could not find a satisfactory version from options: ['>=0.12.0', '<0.13.0', '>=0.11.0', '<0.12.0']
```

### Additional context
Issue first raised in [discourse](https://discourse.snowplow.io/t/snowplow-utils-0-12-1-dbt-package-released/7499/2).
